name: CI

on:
  push:
    paths:
      - "**/*.go"
      - "testdata/*.json"
      - ".github/workflows/buildtest.yml"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.23

      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Build
        run: go build -v ./...

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: build
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Install dependencies
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Test with coverage
        run: |
          go test -cover -coverprofile=coverage.txt -json ./... ./testdata > test-results.json
      
      - name: Generate JUnit report
        if: always()
        run: go-junit-report < test-results.json > test-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results.xml