name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - "**/*.go"
      - ".github/workflows/go.yml"

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.23

      - name: Run Tests with Coverage (Allow Failures)
        run: |
          go test -cover -coverprofile=coverage.txt -json ./... ./testdata > test-results.json || echo "TESTS_FAILED=true" >> $GITHUB_ENV - name: Publish Test Results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.json