name: Go Build and Test

on:
  push:
    paths:
      - "**/*.go"
      - ".github/workflows/go.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.8' # Replace with your required Go version

      - name: Find and process directories with go.mod
        run: |
          go build
          go test -v -cover ./...
          go test -v ./testdata/