name: "Static"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"